### ISSUE TITLE
SQLite busy when editing roster

### ISSUE THREAD

**Issue by ellisjas** [s3529120/septsem12017#30]
Error occures when:
- Change business hours for monday
- Attempt to change Jane Doe's hours for monday

Often results in program freezing.
May be related to the fact that business hours are none by default, yet employee roster is pre-set.
![sqlite-busy](https://cloud.githubusercontent.com/assets/22196200/26403048/0b36fbaa-40d0-11e7-800a-c1194cb0347d.PNG)

**Comment by s3529120** [comment]
No long present as far as i can tell after commit 385fd65
