### ISSUE TITLE
Employee start/end times can only be set to modified business hours

### ISSUE THREAD

**Issue by RobLW** [s3529120/septsem12017#34]
![screen shot 2017-05-25 at 01 42 39](https://cloud.githubusercontent.com/assets/11449623/26412276/8577cc62-40eb-11e7-9b4e-55c672921ce8.png)
![screen shot 2017-05-25 at 01 43 04](https://cloud.githubusercontent.com/assets/11449623/26412277/869dce8e-40eb-11e7-9cf7-8b79d537e246.png)

**Comment by s3529120** [comment]
Fixed with commit 5441c11
