### ISSUE TITLE
Minutes display error

### ISSUE THREAD

**Issue by s3529120** [s3529120/septsem12017#4]
When loading possible times for availabilities the minutes are only correctly generated between 2300 and 2345, all others just display xx:00, with x being the hour.

**Comment by s3529120** [comment]
`   public String[] getPossibleTimes(){
      String[] times=new String[(60/duration)*24];
      
      for(int i=0;i<24;i++){
         for(int j=0;j<(60/duration);j++){
            times[i+j]=String.format("%02d:%02d",i,j*duration);
         }
      }
      return times;
   }
`

**Comment by s3529120** [comment]
Line 39 of AvailabilityController

**Comment by RobLW** [comment]
FIxed
